# Generated by Django 5.0.3 on 2024-04-01 18:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agromart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sellerId',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='agromart.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='acc_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cartId',
            field=models.CharField(default=uuid.uuid4, max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='categoryId',
            field=models.CharField(default=uuid.uuid4, max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='categoryname',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='productId',
            field=models.CharField(default=uuid.uuid4, max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='userId',
            field=models.CharField(default=uuid.uuid4, max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('imageId', models.CharField(default=uuid.uuid4, max_length=150, primary_key=True, serialize=False)),
                ('image', models.ImageField(default='', upload_to='product_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agromart.product')),
            ],
        ),
    ]
