# Generated by Django 5.0.3 on 2024-04-03 21:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agromart', '0002_product_sellerid_user_acc_balance_alter_cart_cartid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoughtItem',
            fields=[
                ('boughtItemId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agromart.product')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agromart.user')),
            ],
        ),
    ]
